/**
 * Emits app/tokens.css from the canonical brand tokens in the sibling app repo.
 *
 *   npm run tokens:emit     writes app/tokens.css
 *   npm run verify:tokens   recomputes the hash and fails on a hand-edit
 *
 * The generated file is committed, because Vercel builds this repo without the
 * sibling app repo present. The hash is what stops the committed copy drifting
 * away from the source once nobody is looking.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  Colors,
  Motion,
  Radius,
  Type,
  platformDrift,
} from '../../cardpulse/src/theme/index';

const OUT = join(process.cwd(), 'app', 'tokens.css');
const OUT_TS = join(process.cwd(), 'lib', 'generated', 'tokens.ts');
const HEADER = '/* @generated by scripts/emit-tokens.ts from cardpulse/src/theme/index.ts. Do not edit by hand. direction: market-tape. emitted-sha256: ';

/** camelCase -> kebab-case, so `textSecondary` becomes `--c-text-secondary`. */
const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

function block(prefix: string, obj: Record<string, string | number>, unit = '') {
  return Object.entries(obj)
    .map(([k, v]) => `  --${prefix}-${kebab(k)}: ${typeof v === 'number' ? `${v}${unit}` : v};`)
    .join('\n');
}

function buildBody() {
  return [
    ':root {',
    '  /* Palette. Dark only, by brand: app.json pins userInterfaceStyle to dark',
    '     and the app ships no light theme, so the site does not invent one. */',
    block('c', Colors),
    '',
    '  /* Type scale. */',
    block('t', Type, 'px'),
    '',
    '  /* One radius scale, applied by role: chips take sm, controls md, panels lg. */',
    block('r', Radius, 'px'),
    '',
    '  /* Motion. */',
    block('m', Motion, 'ms'),
    '}',
    '',
    '@theme inline {',
    '  /* Tailwind v4 reads the same values, so a utility and a raw var cannot',
    '     disagree. Nothing here is a second palette. */',
    Object.keys(Colors).map((k) => `  --color-${kebab(k)}: var(--c-${kebab(k)});`).join('\n'),
    Object.keys(Radius).map((k) => `  --radius-${kebab(k)}: var(--r-${kebab(k)});`).join('\n'),
    '}',
    '',
    `/* Web-only garnish, declared in platformDrift.web. React Native reproduces`,
    `   none of it, so nothing below may be load-bearing. */`,
    ':root {',
    '  --web-hairline: 1px solid var(--c-border);',
    '  --web-panel-shadow: 0 1px 0 0 rgb(255 255 255 / 0.03), 0 24px 48px -24px rgb(0 0 0 / 0.8);',
    '  --web-inner-highlight: inset 0 1px 0 0 rgb(255 255 255 / 0.05);',
    '  --web-tape-fade: linear-gradient(90deg, transparent, var(--c-bg) 92%);',
    '}',
    '',
  ].join('\n');
}

function drift(body: string) {
  const declared = new Set(platformDrift.web);
  const used = new Set(Array.from(body.matchAll(/--web-[a-z-]+/g), (m) => m[0]));
  const undeclared = [...used].filter((p) => !declared.has(p));
  const unused = [...declared].filter((p) => !used.has(p));
  if (undeclared.length || unused.length) {
    throw new Error(
      `platformDrift.web is out of sync with the emitted CSS.\n` +
        (undeclared.length ? `  emitted but not declared: ${undeclared.join(', ')}\n` : '') +
        (unused.length ? `  declared but not emitted: ${unused.join(', ')}\n` : '') +
        `Fix cardpulse/src/theme/index.ts, not this file.`,
    );
  }
}

const verify = process.argv.includes('--verify');
const body = buildBody();
drift(body);
const hash = createHash('sha256').update(body).digest('hex');
const file = `${HEADER}${hash} */\n${body}`;

if (verify) {
  const onDisk = readFileSync(OUT, 'utf8');
  const claimed = onDisk.match(/emitted-sha256: ([0-9a-f]{64}) \*\/\n/);
  const actual = createHash('sha256').update(onDisk.replace(/^.*\*\/\n/, '')).digest('hex');
  if (!claimed) throw new Error('app/tokens.css has no emitted-sha256 header.');
  if (claimed[1] !== actual) {
    throw new Error(
      `app/tokens.css has been hand-edited.\n  header says ${claimed[1]}\n  body hashes to ${actual}\nRun npm run tokens:emit instead.`,
    );
  }
  console.log('tokens.css intact');
} else {
  writeFileSync(OUT, file);

  /* The OG image renders outside a browser, so it cannot read a CSS custom
     property and needs the palette as real JavaScript. Emitting it here keeps
     one source: importing the sibling repo directly would break every Vercel
     build, because that repo is not checked out there. */
  writeFileSync(
    OUT_TS,
    `/* @generated by scripts/emit-tokens.ts. Do not edit by hand. */
` +
      `export const colors = ${JSON.stringify(Colors, null, 2)} as const;
`,
  );

  console.log(`wrote app/tokens.css and lib/generated/tokens.ts (${hash.slice(0, 12)})`);
}
